services:
  x-common: &x-common
    build:
      context: .
    user: "1000:1000"
    volumes:
      - .:/app:z
      - /app/node_modules
      - /app/.expo
      - gradle-cache:/home/node/.gradle
      - android-cache:/home/node/.android
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP:-127.0.0.1}
      - FORCE_COLOR=1
      - ELECTRON_DISABLE_SANDBOX=1
    stdin_open: true
    tty: true

  expo:
    <<: *x-common
    container_name: expo_server
    ports:
      - "8081:8081"
    build:
      target: expo-server

  expo-sshd:
    <<: *x-common
    container_name: expo_sshd
    ports:
      - 50022:50022
    build:
      target: expo-sshd

volumes:
  gradle-cache:
  android-cache:
